artifacts_root: artifacts # created folder to keep all the data in local machine


data_ingestion:
  root_dir: artifacts/data_ingestion # create data_ingestion folder inside i.e on our machine
  source_url: https://github.com/shobhit-003/Database/raw/main/winequality-red.zip # fetching data from this database
  local_data_file: artifacts/data_ingestion/data.zip # here we are giving this dataset name "data", we can give any name to it
  unzip_dir: artifacts/data_ingestion # now we are unzipping the data file



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv # we want to check whether this downloaded data has all the columns or not
  status_file: artifacts/data_validation/status.txt # get the status whether every thing is okay or not



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv