artifacts_root: artifacts # created folder to keep all the data in local machine


data_ingestion:
  root_dir: artifacts/data_ingestion # create data_ingestion folder inside i.e on our machine
  source_url: https://github.com/shobhit-003/Database/raw/main/winequality-red.zip # input -> fetching data from this database
  local_data_file: artifacts/data_ingestion/data.zip # output -> here we are giving this dataset name "data", we can give any name to it
  unzip_dir: artifacts/data_ingestion # output -> now we are unzipping the data file



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv # input -> we want to check whether this downloaded data has all the columns or not
  status_file: artifacts/data_validation/status.txt # output -> get the status whether every thing is okay or not



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv # input -> we need downloaded data, we will create output i.e. train.csv and test.csv
  # or we can empty train.csv and test.csv here also like
  # train_data: artifacts/data_transformation/train.csv
  # test_data: artifacts/data_transformation/test.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv # input
  test_data_path: artifacts/data_transformation/test.csv # input
  model_name: model.joblib # output



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv # input
  model_path: artifacts/model_trainer/model.joblib # input
  metric_file_name: artifacts/model_evaluation/metrics.json # output
